"""
Django settings for statbov project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from .assets import *
from .databases import *
from .environment import *
from .i18n import *
from .installed_apps import *
from .messages import *
from .middlewares import *
from .security import *
from .templates import *
